name = "lotto-analysis-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "lotto_db"
database_id = "d879aa99-d304-4001-b3d9-67ab6605de57"

[triggers]
crons = ["30 21 * * 6"] # Every Saturday 21:30 KST
